controller_manager:
  ros__parameters:
    update_rate: 100

    pole_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

pole_position_controller:
  ros__parameters:
    joints:
    - base_to_pole
    interface_name: position